### ISSUE TITLE
gwt-user.jar

### ISSUE THREAD

**Issue by jjdestef3** [Putnami/putnami-gradle-plugin#23]
Hi,

Just started using the plugin in intellij. When I do a build the gwt-user.jar is not automatically included with other dependencies in the war file. I'm not using the jetty integration but instead I deploy to wildfly and use the codeServer for debugging. If I put the jar in the WEB-INF/lib folder then it does get deployed. Is this the default behavior?

**Comment by jgleoj23** [comment]
This isn't the default behavior. I know because I didn't have that problem.
It doesn't get my dependencies automatically either though. Refreshing
works for me. Just go the gradle window and click the refresh button. Here's
the help page on the refresh button
<https://www.google.com/search?q=gradle+refresh+intellij&oq=gradle+refresh+intellij&aqs=chrome..69i57.4291j0j4&sourceid=chrome&es_sm=122&ie=UTF-8>.
If that doesn't work you could try testing it on Jetty. Are you using some
sort of wildfly plugin for gradle that's analogous to the jetty plugin for
gradle? Also, try checking to see if it gets other dependencies you add.

**Comment by fdumay** [comment]
Hi,

From what I know, the gwt-user.jar should not be in the war. 
On an other side, you may need the gwt-servlet.jar (i.e: for RPC) 
To include it, you must set `gwtServletLib = true``
If you really need the gwt-user you can add the dependency explicitly:

```
dependecies{
   compile "com.google.gwt:gwt-user:2.7.0"
}
```

How do you deploy your war in wildfly? Is there any gradle plugin or maybe via IntelliJ?

**Comment by jjdestef3** [comment]
Hi, 

Thanks for the responses. My error in the gradle build file caused the issue. As far as deployment to wildfly I have a gradle task that I run that depends on the build to copy the war file to the Wildfly deployment directory. There is a cargo plugin I think and I'm going to investigate that next.

Thanks

**Comment by jjdestef3** [comment]
Oh,

One other thing, that for your hard work developing the gradle build for gwt and sharing. This is really great.

Thanks

**Comment by fdumay** [comment]
@jjdestef3 You're welcome, I love building some things usefull for others :)
If you like it, Can you please add a star to the project :D
